### ISSUE TITLE
Path Names get f***ed up

### ISSUE THREAD

**Issue by RvdHout** [coax/hmailserver-webadmin#38] opened 2021-04-23 23:10 UTC
Don't know if this is reported before, but if you, for example enable plus addressing for a domain and that specific domain uses DKIM signing te path get stripped from it slashes after saving

this:
`C:\Program Files\hMailServer\DKIM\dkim.domain.com.mail.key`
becomes:

`C:Program FileshMailServerDKIMdkim.domain.com.mail.key`

Similar happens to External VirusScan and/or ClamWin path names (also note the limited maxlength="60" here that might be troublesome)

**Comment by coax** [comment] 2021-04-24 08:24
Should be fixed now thanks to @tunis78

**Comment by RvdHout** [comment] 2021-04-24 08:28
@coax 
That is a fix related to the recent hm_dmarcreports.php pull request and has nothing to do with the issue described above

**Comment by coax** [comment] 2021-05-02 10:14
I didn't read carefully, sorry. In any case, I can't reproduce/test it as I don't use plus addressing nor external VirusScan/ClamWin. Can you create pull reqest with the fix?

**Comment by RvdHout** [comment] 2021-05-02 12:08
Hi coax,

The fix could be fairly easy, eg: remove stripslashes (actually you can completely delete lines 26/27 as get_magic_quotes_gpc() isn't used anymore stripslashes seems redundant too, not?
https://github.com/coax/hmailserver-webadmin/blob/master/hMailAdmin/include/functions.php#L26-L27

```
	//if (get_magic_quotes_gpc())
		$retval = stripslashes($retval);
```

**Alternatively**, when you think stripslashes should remain you could create an alternative function to get Path names without the use of stripslashes,

```
function hmailGetPath($p_varname, $p_defaultvalue = null) {
	$retval = $p_defaultvalue;
	if(isset($_GET[$p_varname])) {
		$retval = $_GET[$p_varname];
	} else if (isset($_POST[$p_varname])) {
		$retval = $_POST[$p_varname];
	} else if (isset($_REQUEST[$p_varname])) {
		$retval	= $_REQUEST[$p_varname];
	}
	return $retval;
}
```
On various pages hmailGetVar() has to be replaced with hmailGetPath() to make this work

**Comment by coax** [comment] 2021-05-02 12:30
`/include/functions.php`
stripslashes have been disabled

`hm_smtp_antivirus.php`
External virus scanner > Scanner executable input field maxlength increased from 60 to 255

**Closed as completed** 2021-05-02 20:48 UTC
